# Generated by Django 5.1.4 on 2025-01-13 02:35

import django.db.models.deletion
import timescale.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('user_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_ts', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_ts'],
            },
        ),
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=255, unique=True)),
                ('schema', models.JSONField(help_text='JSON Schema defining the structure and validation rules for the metric')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['series'], name='metrics_met_series_a49b5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 week')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.metrictype')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series_data', to='metrics.session')),
            ],
            options={
                'indexes': [models.Index(fields=['time', 'series', 'session'], name='metrics_tim_time_fa4eac_idx')],
            },
        ),
    ]
