# Generated by Django 5.1.4 on 2025-01-10 22:22

import django.db.models.deletion
import timescale.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=255, unique=True)),
                ('value_type', models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('rgb', 'RGB Color')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['series'], name='metrics_met_series_a49b5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('user_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ts', models.DateTimeField(db_index=True)),
                ('value', models.TextField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series_data', to='metrics.metrictype')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'series', 'ts'], name='metrics_tim_user_id_af9c2e_idx'), models.Index(fields=['session_id', 'series', 'ts'], name='metrics_tim_session_a48da4_idx'), models.Index(fields=['series', 'ts'], name='metrics_tim_series__c31844_idx')],
            },
        ),
    ]
