FROM python:3.10.12

RUN apt-get update && apt-get install -y inotify-tools gdal-bin
RUN apt-get update && apt-get install -yy gcc build-essential graphviz libgraphviz-dev

ENV PYTHONUNBUFFERED 1

ADD requirements.dev.txt .
ADD requirements.txt .
RUN pip install -r requirements.dev.txt

WORKDIR /app

ENV PYTHONPATH "${PYTHONPATH}:/app/src"